### ISSUE TITLE
Model notifies observers upon its load leading to the retain loop

### ISSUE THREAD

**Issue by igavrysh** [uber/signals-ios#41]
I have a model, which notifies its observers upon its load. However, it is not possible to send itself in onLoad signal since it will lead to retain loop, e.g. Model holds strongly onLoad signal, whereas signal holds Model strongly as it is passed in .fire(model, error) method. Please, find mock listing below:

```
CreateSignalType(UBModelLoadResult, UBLoadableModel   model, NSError    error)

@interface UBLoadableModel

@property (nonatomic, readonly) UBSignal<UBModelLoadResultSignal> *onModelLoaded;
@property (nonatomic, readonly) UBSignal<EmptySignal> *onModelLoading;

@end

@implementation UBLoadableModel

- (instancetype)init {
  self = [super init];
  if (self) {
    _onModelLoaded = (UBSignal<UBModelLoadResultSignal> *)
         [[UBSignal alloc] initWithProtocol:@protocol(UBModelLoadResultSignal)];
    _onModelLoading = (UBSignal<EmptySignal> *)
         [[UBSignal alloc] initWithProtocol:@protocol(EmptySignal)];
   }
   return self;
}

- (void)load
{
  // Signal all listeners we're done loading
  self.onModelLoading.fire();
  
  // Signal all listeners that we have data or an error
  // This line leads to retain loop
  self.onModelLoaded.fire(self, nil);
}

@end

@interface MyClass ()
@property (nonatomic, strong) UBLoadableModel *model	
	
@end	
	
	
@implementation MyClass

- (void)run {
	[model.onModelLoaded addObserver:self callback:^(typeof(self) self, UBLoadableModel model, NSError error) {
		NSLog(@"Loaded")
	}];	
}

@end

```
There are two possible ways to resolve this issue:
- send nil in the fire method, e.g.  .fire(nil. error). A drawback for this solution is that the class that doesn't contain Model as a property won't be able to figure out which model has loaded.
- wrap self into class with weak property which should hold Model, then send in .fire(...) method with this weakified object.

The both of them are ugly. Can you share your knowledge of handling these kind of retain loops?

**Comment by artman** [comment]
It's always unnecessary to have a signal fire its host object, since any observers will always have access to it (otherwise they would not be able to get to the signal).

Singals pass in a weakified observer as the first argument of the callback block precisely to help you with not creating cyclical references.

These few changes will fix your problems:

Don't pass in the model in your signal:
```
CreateSignalType(UBModelLoadResult, NSError    error)
```

Utilize the weakened self to access your model in the observer block:
```
- (void)run {
	[model.onModelLoaded addObserver:self callback:^(typeof(self) self, NSError error) {
		NSLog(self.model) // self is weakified by Signals, so you can safely use it.
	}];	
}
```
