### ISSUE TITLE
Add a sample app

### ISSUE THREAD

**Issue by aaronbrethorst** [uber/signals-ios#6]
This looks really cool! A sample app showing best practices in consuming this library would be much appreciated.

**Comment by KimDarren** [comment]
:+1:

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
It can help solve the problems that IOS cannot be installed and verified
https://urlzs.com/44zCx
